// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! This file is automatically generated by build_applies. !!!
// !!! do not make any manual changes to this file.           !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef __APPLIES_HH__
#define __APPLIES_HH__

extern const char *applies_table[];

// the folowing must be the first character of __INIT
#define APPLY___INIT_SPECIAL_CHAR		'#'

#define NUM_MASTER_APPLIES	0

#endif
